apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocapstone-dep
spec:
  selector:
    matchLabels:
      app: gocapstone-dep
  template:
    metadata:
      labels:
        app: gocapstone-dep
    spec:
      containers:
        - name: capstone-app
          image: sam72/capstone:v1
          imagePullPolicy: Always
          ports:
            - name: capstone
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gocapstone-svc
  labels:
    name: gocapstone-svc
spec:
  selector:
    app: gocapstone-dep
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
