version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.16.0

    steps:
      # - checkout

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "go.mod" }}
      #       - v1-dependencies-

      # - run:
      #     name: Install dependencies for the next build steps
      #     command: |
      #       make setup

      #       wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
      #       chmod +x /bin/hadolint

      # - save_cache:
      #     paths:
      #       - .
      #     key: v1-dependencies-{{ checksum "go.mod" }}

      # - run:
      #     name: Lint the Dockerfile and vet the Go code
      #     command: |
      #       make lint
      
      # - run:
      #     name: Compile the Go code to ensure it builds correctly
      #     command: |
      #       go build -o capstone-server .
      
      # - run:
      #     name: Run the Go unit tests
      #     command: |
      #       make test

      # - setup_remote_docker:
      #     version: 19.03.13
      
      - run:
          name: Install Docker and it's dependencies
          command: |
            apt-get install sudo

            sudo apt update

            sudo apt install apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
            sudo apt update
            apt-cache policy docker-ce

            sudo apt install docker-ce

            sudo systemctl status docker

      # - run:
      #     name: Build the Docker image
      #     command: |
      #       docker build -t capstone:v1 .
      #       docker ls

      # - run:
      #     name: Tag and push the image to Docker Hub
      #     command: |
      #       dockerpath=${DH_USERNAME}/capstone:v1

      #       echo "Docker ID and Image: $dockerpath"

      #       docker login -u $DH_USERNAME -p $DH_PASSWORD

      #       docker tag capstone:v1 $dockerpath

      #       docker push $dockerpath

workflows:
  default:
    jobs:
      - build