version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.16.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "go.mod" }}
            - v1-dependencies-

      - run:
          name: Install dependencies for the next build steps
          command: |
            make setup

            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      - save_cache:
          paths:
            - .
          key: v1-dependencies-{{ checksum "go.mod" }}

      - run:
          name: Lint the Dockerfile and vet the Go code
          command: |
            make lint
      
      - run:
          name: Run the Go unit tests
          command: |
            make test

      - setup_remote_docker:
          version: 19.03.13

workflows:
  default:
    jobs:
      - build