version: 2.1
jobs:
  # build:
  #   docker:
  #     - image: golang:1.16.0

  #   steps:
      # - checkout

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "go.mod" }}
      #       - v1-dependencies-

      # - run:
      #     name: Install dependencies for the next build steps
      #     command: |
      #       make setup

      #       wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
      #       chmod +x /bin/hadolint

      # - save_cache:
      #     paths:
      #       - .
      #     key: v1-dependencies-{{ checksum "go.mod" }}

      # - run:
      #     name: Lint the Dockerfile and vet the Go code
      #     command: |
      #       make lint
      
      # - run:
      #     name: Compile the Go code to ensure it builds correctly
      #     command: |
      #       go build -o capstone-server .
      
      # - run:
      #     name: Run the Go unit tests
      #     command: |
      #       make test

      # - setup_remote_docker:
      #     version: 19.03.13
      
      # - run:
      #     name: Install Docker and it's dependencies
      #     command: |
      #       apt-get update
      #       apt-get -y install sudo

      #       sudo apt-get update

      #       sudo apt-get -y install \
      #         apt-transport-https \
      #         ca-certificates \
      #         curl \
      #         gnupg-agent \
      #         software-properties-common
            
      #       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

      #       sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      #       sudo add-apt-repository "deb http://ftp.de.debian.org/debian sid main"
      #       sudo apt-get update && sudo apt-get -y upgrade

      #       sudo apt-get -y -f install libseccomp2

      #       sudo apt-get -y install docker-ce docker-ce-cli containerd.io

  build-image:
    docker:
      - image: python:3.7.3-stretch
      
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      - run:
          name: Install Docker and it's dependencies
          command: |
            apt-get update && apt-get -y install sudo
            sudo apt-get update
            sudo apt-get -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" -y
            sudo apt-get update
            sudo apt-get -y install docker-ce docker-ce-cli containerd.io

      - run:
          name: Build the Docker image
          command: |
            docker build -t capstone:v1 .
            docker images

      - run:
          name: Tag and push the image to Docker Hub
          command: |
            dockerpath="$DH_USERNAME/capstone:v1"
            echo "PATH BUILT SUCCESSFULLY"

            docker login -u "$DH_USERNAME" -p "$DH_PASSWORD"
            echo "LOGGED IN SUCCESSFULLY"

            docker tag capstone:v1 $dockerpath
            echo "IMAGE TAGGED SUCCESSFULLY"

            docker push $dockerpath
            echo "UPLOAD SUCCESSFUL"

workflows:
  default:
    jobs:
      # - build
      - build-image