version: 2.1
jobs:
  build-code:
    docker:
      - image: golang:1.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "go.mod" }}
            - v1-dependencies-
      - run:
          name: Install dependencies for the next build steps
          command: |
            make setup
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - .
          key: v1-dependencies-{{ checksum "go.mod" }}
      - run:
          name: Lint the Dockerfile and vet the Go code
          command: |
            make lint
      - run:
          name: Compile the Go code to ensure it builds correctly
          command: |
            go build -o capstone-server .
      - run:
          name: Run the Go unit tests
          command: |
            make test

  build-image:
    docker:
      - image: python:3.7.3-stretch # I simply couldn't get the Docker steps to work with any other image...
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run:
          name: Install Docker and it's dependencies
          command: |
            apt-get update && apt-get -y install sudo
            sudo apt-get update
            sudo apt-get -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" -y
            sudo apt-get update
            sudo apt-get -y install docker-ce docker-ce-cli containerd.io
      - run:
          name: Build the Docker image
          command: |
            docker build -t capstone:v1 .
            docker images
      - run:
          name: Tag and push the image to Docker Hub
          command: |
            dockerpath="$DH_USERNAME/capstone:v1"
            docker login -u "$DH_USERNAME" -p "$DH_PASSWORD"
            docker tag capstone:v1 $dockerpath
            docker push $dockerpath

  deploy-eks:
    docker:
      - image: ubuntu:20.04

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get -y install sudo
            sudo apt-get update && sudo apt-get -y upgrade

            sudo apt-get -y install curl tar unzip

            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

            aws --version

workflows:
  default:
    jobs:
      # - build-code
      # - build-image:
      #     requires: [build-code]
      - deploy-eks:
          # requires: [build-image]
          filters:
            branches:
              only:
                - main